# sshd

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ ssh_pub_key_path }}/*.pub"

- name: Set authorized key taken from file to root
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ inventory_dir }}/*.pub"
  when: (enable_root_login | bool) and (ansible_user != "root")

- name: Ensure PubkeyAuthentication is set to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present

- name: Ensure AuthorizedKeysFile is set correctly
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysFile"
    line: "AuthorizedKeysFile .ssh/authorized_keys"
    state: present

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  when: disable_password_login | bool

- name: Disable keyboard interactive authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^KbdInteractiveAuthentication"
    line: "KbdInteractiveAuthentication no"
    state: present
  when: disable_password_login | bool

- name: Disable challenge response authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
    state: present
  when: disable_password_login | bool

- name: Enable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"
    state: present
  when: not disable_password_login | bool

- name: Enable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin yes"
    state: present
  when: (enable_root_login | bool) or (ansible_user == "root")

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  when: (not enable_root_login | bool) and (ansible_user != "root")

- name: Reload ssh service
  service:
    name: ssh
    state: reloaded
